#!/bin/bash

# Manage MySQL log

QUERYLOG=`grep log /etc/my.cnf | awk -F "=" '{print $2}'`

function sqlfollow {
    tail -f $QUERYLOG | grep ${1-Query}
}

case $1 in
   clear)
       echo '' > $QUERYLOG
   ;;
   follow)
       sqlfollow $2
   ;;
   '')
       sqlfollow
   ;;
   *)
       echo "Usage: sqlog (clear|follow)";
       set -e;
   ;;
esac
